---

stages:
  - lint
  - test


cache:
  paths:
    - vendor/


php-cs-fixer:
  stage: lint
  image: php:7.4
  before_script:
    - curl -L https://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -o php-cs-fixer
    - chmod a+x php-cs-fixer
  script:
    - ./php-cs-fixer fix -v --dry-run --diff .
  tags:
    - docker


phpunit:
  stage: test
  image: lbausch/laravel-ci:v1.0.0
  before_script:
    - composer install --ansi --no-interaction --no-progress
  script:
    - ./vendor/bin/phpunit --coverage-text --color=never
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  tags:
    - docker
